name: Build Only (Manual Deploy)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Astro
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 30

      - name: Build summary
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Artifacts uploaded"
          echo ""
          echo "To enable automatic deployment:"
          echo "1. Go to Settings → Pages"
          echo "2. Set Source to 'GitHub Actions'"
          echo "3. Use the 'Deploy to GitHub Pages' workflow"
