name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        continue-on-error: true
        run: |
          if [ -f "tsconfig.json" ]; then
            echo "🔍 Running TypeScript type check..."
            npx astro check || echo "⚠️ Type check completed with errors - review required"
          else
            echo "⚠️ No tsconfig.json found, skipping type check"
          fi

      - name: Format check
        continue-on-error: true
        run: |
          if [ -f ".prettierrc" ]; then
            echo "🎨 Checking code formatting..."
            npx prettier --check "src/**/*.{ts,tsx,js,jsx}" || echo "⚠️ Formatting issues found - run 'npm run format' to fix"
          else
            echo "⚠️ No Prettier config found, skipping format check"
          fi

      - name: Build check
        run: |
          echo "🔧 Testing build process..."
          npm run build
          echo "✅ Build completed successfully"
